---
- hosts: all
  gather_facts: false
  tasks:

    - name: "List all known variables and facts"
      debug:
        var: hostvars[inventory_hostname]
  
    - set_fact:
        nejaka_promenna: dobra
      delegate_to: 16.170.146.116
