---
- hosts: all
  gather_facts: false
  vars:
    vault_namespace_domain: aws
    vault_instance_name: jskacel-win
  tasks:

    - name: "List all known variables and facts"
      debug:
        msg: >-
            {{ lookup('hashi_vault', 'secret=secret/data/{{ vault_namespace_domain }}/{{ vault_instance_name }}:data')['userpwd'] }}

    - set_fact:
        nejaka_promenna: dobra
      delegate_to: 16.170.146.116
