---
- hosts: all
  gather_facts: false
  vars:
    vault_namespace_domain: aws
    vault_instance_name: jskacel-win
  tasks:

    - name: "List all known variables and facts"
      debug:
        msg: "{{ lookup('hashi_vault', 'secret=secret/data/aws/jskacel-win', token='hvs.V5PRDlfhFyKzj7mhhufUrRfi', url='http://192.168.100.18:8200')}}"

    - set_fact:
        nejaka_promenna: dobra
      delegate_to: 16.170.146.116
