---
- hosts: localhost
  gather_facts: false
  tasks:
  - debug:
      msg: "{{ ansible_user }}"
    delegate_to: 192.168.100.18
    delegate_facts: true

  - set_fact:
      nejaka_promenna: dobra
      cacheable: true
    delegate_to: 192.168.100.18
    delegate_facts: True
